jobs:
  include:
    - stage: publish
      language: node_js
      install:
        - npm ci
        # Install a new version of the openshift cli
        - mkdir -p /opt/openshift
        - wget -qO- https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz | tar xvzf - -C /opt/openshift --strip-components=1
        - export PATH=$PATH:/opt/openshift
        - echo $OPENSHIFT_CERT | base64 --decode > /tmp/openshift.crt
      script: npx semantic-release

stages:
  - name: publish
    if: (branch ==master AND type != pull_request)